### ISSUE TITLE
The YAML file is invalid

### ISSUE THREAD

**Issue by Kaizo107** [MrCee/Synology-Homebrew#12]
```
Starting Full Setup...
==> Running in non-interactive mode because `$NONINTERACTIVE` is set.
==> Checking for `sudo` access (which may request your password)...
/var/services/homes/Kaizo107/Synology-Homebrew/install-synology-homebrew.sh: line 182: /home/linuxbrew/.linuxbrew/bin/brew: No such file or directory
/bin/ls: cannot access '/home/linuxbrew/.linuxbrew/opt/gcc/bin/gcc-*': No such file or directory
ln: failed to create symbolic link '/home/linuxbrew/.linuxbrew/bin/gcc': No such file or directory
/var/services/homes/Kaizo107/.profile: line 35: /home/linuxbrew/.linuxbrew/bin/brew: No such file or directory
--------------------------PATH SET-------------------------------
/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/opt/binutils/bin:/home/linuxbrew/.linuxbrew/opt/glibc/bin:/home/linuxbrew/.linuxbrew/opt/glibc/sbin:/home/linuxbrew/.linuxbrew/lib/ruby/gems/3.3.0/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
-----------------------------------------------------------------
Error: The YAML file '/volume1/homes/Kaizo107/Synology-Homebrew/config.yaml' is invalid.
```

**Comment by MrCee** [comment]
I'm not sure how you have cloned the repository, but it looks like it's incomplete from the beginning.
I would delete the folder and try again. Also make sure you have a scheduled task created to persist the volume after a restart. What model NAS do you have? 

There should be more terminal output than that so if you could provide all of it that will help.

**Comment by Kaizo107** [comment]
Device is a Synology Diskstation DS223j, running DSM 7.2.1-69057 Update 5

When creating the mount task, I don't have the option to choose boot-up as an option, it's only intervals or one-time. Ran the task, deleted the homebrew folder, now when I SSH in, I get the same error about LinuxBrew missing before even trying to clone the repo with your `git clone https://github.com/MrCee/Synology-Homebrew.git ~/Synology-Homebrew && \
~/Synology-Homebrew/install-synology-homebrew.sh.` 

Proceeding yields the same result. There is no additional output, unless it's being logged somewhere.

**Comment by Kaizo107** [comment]
I'm not sure my unit can even run Homebrew, but I've reached the end result of being able to run Go scripts without needing it, so, closing the issue, sorry to bother.

**Comment by MrCee** [comment]
No problem. I've updated the repository with clearer instructions. By all accounts, your DS223j should be good to go with Triggered Tasks.
