### ISSUE TITLE
Please Help! The YAML file is invalid

### ISSUE THREAD

**Issue by tanawitsu** [MrCee/Synology-Homebrew#13]
I'm using DS920+ trying to install Synology-Homebrew

- The Synology Task Scheduler has been set.
- SSH with iTerm2
- I've deleted the folder and tried several times but same results

```shell
DSM Version: 7.2.2-72806 Update 2
CPU: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
Architecture: x86_64

Starting Minimal Install...
==> Running in non-interactive mode because `$NONINTERACTIVE` is set.
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew
==> The following new directories will be created:
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/etc
/home/linuxbrew/.linuxbrew/include
/home/linuxbrew/.linuxbrew/lib
/home/linuxbrew/.linuxbrew/sbin
/home/linuxbrew/.linuxbrew/share
/home/linuxbrew/.linuxbrew/var
/home/linuxbrew/.linuxbrew/opt
/home/linuxbrew/.linuxbrew/share/zsh
/home/linuxbrew/.linuxbrew/share/zsh/site-functions
/home/linuxbrew/.linuxbrew/var/homebrew
/home/linuxbrew/.linuxbrew/var/homebrew/linked
/home/linuxbrew/.linuxbrew/Cellar
/home/linuxbrew/.linuxbrew/Caskroom
/home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /usr/bin/install -d -o tanawitsu -g users -m 0755 /home/linuxbrew/.linuxbrew
==> /usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/chmod ug=rwx /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/chmod go-w /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions
==> /usr/bin/sudo /bin/chown tanawitsu /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/chgrp users /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew/Homebrew
==> /usr/bin/sudo /bin/chown -R tanawitsu:users /home/linuxbrew/.linuxbrew/Homebrew
==> Found Git: /usr/local/bin/git
==> Found cURL: /bin/curl
==> Downloading and installing Homebrew...
/bin/bash: line 920: cd: /home/linuxbrew/.linuxbrew/Homebrew: Permission denied
/bin/bash: line 920: return: can only `return' from a function or sourced script
/usr/.git: Permission denied
Failed during: /usr/local/bin/git -c init.defaultBranch=master init --quiet
/var/services/homes/tanawitsu/Synology-Homebrew/install-synology-homebrew.sh: line 224: /home/linuxbrew/.linuxbrew/bin/brew: Permission denied
/var/services/homes/tanawitsu/Synology-Homebrew/install-synology-homebrew.sh: line 236: .profile-templates/synology-profile-template: No such file or directory
--------------------------PATH SET-------------------------------
/opt/bin:/opt/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
-----------------------------------------------------------------
Error: The YAML file './config.yaml' is invalid.
⚠️ Script exited with code 1.
🗑️ Removing sudoers file at '/etc/sudoers.d/custom_homebrew_sudoers'...
🗑️ Sudoers file removed.
🔒 Revoking sudo access...
🔒 Sudo access revoked.
```

**Comment by MrCee** [comment]
Thanks for pointing this out. I have amended the last commit, can you do a fresh pull of the repository and let me know how you go.

**Comment by tanawitsu** [comment]
Still getting errors

`DSM Version: 7.2.2-72806 Update 2
CPU: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
Architecture: x86_64

Starting Full Setup...
==> Running in non-interactive mode because `$NONINTERACTIVE` is set.
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew
==> The following existing directories will be made writable by user only:
/home/linuxbrew/.linuxbrew/share/zsh
/home/linuxbrew/.linuxbrew/share/zsh/site-functions
==> /usr/bin/sudo /bin/chmod u+rwx /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions
==> /usr/bin/sudo /bin/chmod go-w /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions
==> /usr/bin/sudo /bin/chown -R tanawitsu:users /home/linuxbrew/.linuxbrew/Homebrew
==> Found Git: /usr/local/bin/git
==> Found cURL: /bin/curl
==> Downloading and installing Homebrew...
==> Updating Homebrew...
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:ddc6e7963b71b78263e2f5c80464a5ed563897a2b03c22e86b1ec14548de800b
######################################################################### 100.0%
==> Pouring portable-ruby-3.3.6.x86_64_linux.bottle.tar.gz
Warning: /home/linuxbrew/.linuxbrew/bin is not in your PATH.
  Instructions on how to configure your shell for Homebrew
  can be found in the 'Next steps' section below.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Fetching dependencies for glibc: linux-headers@5.15
==> Fetching linux-headers@5.15
==> Fetching glibc
==> Fetching dependencies for gcc: gmp, isl, mpfr, libmpc, lz4, xz, zlib, zstd and binutils
==> Fetching gmp
==> Fetching isl
==> Fetching mpfr
==> Fetching libmpc
==> Fetching lz4
==> Fetching xz
==> Fetching zlib
==> Fetching zstd
==> Fetching binutils
==> Fetching gcc
==> Installing dependencies for glibc: linux-headers@5.15
==> Installing glibc dependency: linux-headers@5.15
🍺  /home/linuxbrew/.linuxbrew/Cellar/linux-headers@5.15/5.15.174: 961 files, 5.7MB
==> Installing glibc
==> /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1/sbin/ldconfig
==> Installing locale data for en_US.UTF-8 en_US.utf8
==> /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1/bin/localedef -i en_US -f UTF
==> /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1/bin/localedef -i en_US -f UTF
==> Caveats
The Homebrew's Glibc has been installed with the following executables:
  /home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd
  /home/linuxbrew/.linuxbrew/opt/glibc/bin/ld.so
  /home/linuxbrew/.linuxbrew/opt/glibc/sbin/ldconfig

By default, Homebrew's linker will not search for the system's libraries. If you
want Homebrew to do so, run:

  cp "/home/linuxbrew/.linuxbrew/etc/ld.so.conf.d/99-system-ld.so.conf.example" "/home/linuxbrew/.linuxbrew/etc/ld.so.conf.d/99-system-ld.so.conf"
  brew postinstall glibc

to append the system libraries to Homebrew's ld search paths. This is risky and
**highly not recommended**, because it may cause linkage to Homebrew libraries
mixed with system libraries.

glibc is keg-only, which means it was not symlinked into /home/linuxbrew/.linuxbrew,
because it can shadow system glibc if linked.

If you need to have glibc first in your PATH, run:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/glibc/bin:$PATH"' >> ~/.profile
  echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/glibc/sbin:$PATH"' >> ~/.profile

For compilers to find glibc you may need to set:
  export LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/glibc/lib"
  export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/glibc/include"
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1: 1,405 files, 47.1MB
==> Running `brew cleanup glibc`...
==> Installing dependencies for gcc: gmp, isl, mpfr, libmpc, lz4, xz, zlib, zstd and binutils
==> Installing gcc dependency: gmp
🍺  /home/linuxbrew/.linuxbrew/Cellar/gmp/6.3.0: 24 files, 3.9MB
==> Installing gcc dependency: isl
🍺  /home/linuxbrew/.linuxbrew/Cellar/isl/0.27: 75 files, 9.9MB
==> Installing gcc dependency: mpfr
🍺  /home/linuxbrew/.linuxbrew/Cellar/mpfr/4.2.1: 32 files, 3.9MB
==> Installing gcc dependency: libmpc
🍺  /home/linuxbrew/.linuxbrew/Cellar/libmpc/1.3.1: 14 files, 644.1KB
==> Installing gcc dependency: lz4
🍺  /home/linuxbrew/.linuxbrew/Cellar/lz4/1.10.0: 24 files, 799.9KB
==> Installing gcc dependency: xz
🍺  /home/linuxbrew/.linuxbrew/Cellar/xz/5.6.3: 97 files, 2MB
==> Installing gcc dependency: zlib
🍺  /home/linuxbrew/.linuxbrew/Cellar/zlib/1.3.1: 14 files, 477.2KB
==> Installing gcc dependency: zstd
🍺  /home/linuxbrew/.linuxbrew/Cellar/zstd/1.5.6: 32 files, 2.9MB
==> Installing gcc dependency: binutils
==> Fetching dependencies for git: libunistring, acl, icu4c@76, ncurses, readline, libxml2, gettext, bzip2, binutils, gcc, pcre2, ca-certificates, openssl@3, brotli, libnghttp2, libssh2, rtmpdump, libidn2, libedit, krb5, libxcrypt, sqlite, util-linux, openldap, curl and expat
==> Fetching libunistring
==> Fetching acl
==> Fetching icu4c@76
==> Fetching ncurses
==> Fetching readline
==> Fetching libxml2
==> Fetching gettext
==> Fetching bzip2
==> Fetching binutils
==> Fetching gcc
==> Installing pcre2 dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
==> Fetching dependencies for ruby: binutils, gcc, libyaml, ca-certificates, openssl@3, gperf, libffi and libxcrypt
==> Fetching binutils
==> Fetching gcc
==> Installing libyaml dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
==> Fetching dependencies for clang-build-analyzer: mpdecimal, ca-certificates, openssl@3, ncurses, readline, sqlite, berkeley-db@5, libedit, krb5, libtirpc, libnsl, bzip2, expat, libffi, libxcrypt, unzip, python@3.13, binutils, gcc, z3, elfutils and llvm
==> Fetching mpdecimal
==> Fetching ca-certificates
==> Fetching openssl@3
==> Fetching ncurses
==> Fetching readline
==> Fetching sqlite
==> Fetching berkeley-db@5
==> Fetching libedit
==> Fetching krb5
==> Fetching libtirpc
==> Fetching libnsl
==> Fetching bzip2
==> Fetching expat
==> Fetching libffi
==> Fetching libxcrypt
==> Fetching unzip
==> Fetching python@3.13
==> Fetching binutils
==> Fetching gcc
==> Installing z3 dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
==> Fetching dependencies for zsh: bzip2, binutils, gcc, pcre and ncurses
==> Fetching bzip2
==> Fetching binutils
==> Fetching gcc
==> Installing pcre dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
==> Fetching dependencies for yq: binutils and gcc
==> Fetching binutils
==> Fetching gcc
==> Installing yq dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
/bin/ls: cannot access '/home/linuxbrew/.linuxbrew/opt/gcc/bin/gcc-*': No such file or directory
--------------------------PATH SET-------------------------------
/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/opt/binutils/bin:/home/linuxbrew/.linuxbrew/opt/glibc/bin:/home/linuxbrew/.linuxbrew/opt/glibc/sbin:/home/linuxbrew/.linuxbrew/lib/ruby/gems/*/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
-----------------------------------------------------------------
Error: The YAML file './config.yaml' is invalid.
⚠️ Script exited with code 1.
🗑️ Removing sudoers file at '/etc/sudoers.d/custom_homebrew_sudoers'...
🗑️ Sudoers file removed.
🔒 Revoking sudo access...
🔒 Sudo access revoked.`

**Comment by MrCee** [comment]
Thanks, I do see progress.
If you would like to try the following while I look into it, please try totally removing everything using the uninstall script and clear some caches and then pull the repository again.....

```
~/Synology-Homebrew/uninstall-synology-homebrew.sh
rm -rf ~/Synology-Homebrew
rm -rf ~/.local ~/.cache
```

**Comment by tanawitsu** [comment]
I've followed your suggestion but no luck.

```
DSM Version: 7.2.2-72806 Update 2
CPU: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
Architecture: x86_64

Starting Minimal Install...
==> Running in non-interactive mode because `$NONINTERACTIVE` is set.
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew
==> The following new directories will be created:
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/etc
/home/linuxbrew/.linuxbrew/include
/home/linuxbrew/.linuxbrew/lib
/home/linuxbrew/.linuxbrew/sbin
/home/linuxbrew/.linuxbrew/share
/home/linuxbrew/.linuxbrew/var
/home/linuxbrew/.linuxbrew/opt
/home/linuxbrew/.linuxbrew/share/zsh
/home/linuxbrew/.linuxbrew/share/zsh/site-functions
/home/linuxbrew/.linuxbrew/var/homebrew
/home/linuxbrew/.linuxbrew/var/homebrew/linked
/home/linuxbrew/.linuxbrew/Cellar
/home/linuxbrew/.linuxbrew/Caskroom
/home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /usr/bin/install -d -o tanawitsu -g users -m 0755 /home/linuxbrew/.linuxbrew
==> /usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/chmod ug=rwx /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/chmod go-w /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions
==> /usr/bin/sudo /bin/chown tanawitsu /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/chgrp users /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew/Homebrew
==> /usr/bin/sudo /bin/chown -R tanawitsu:users /home/linuxbrew/.linuxbrew/Homebrew
==> Found Git: /usr/local/bin/git
==> Found cURL: /bin/curl
==> Downloading and installing Homebrew...
==> Updating Homebrew...
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:ddc6e7963b71b78263e2f5c80464a5ed563897a2b03c22e86b1ec14548de800b
########################################################################################################################################################################################################################################## 100.0%
==> Pouring portable-ruby-3.3.6.x86_64_linux.bottle.tar.gz
Warning: /home/linuxbrew/.linuxbrew/bin is not in your PATH.
  Instructions on how to configure your shell for Homebrew
  can be found in the 'Next steps' section below.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Fetching dependencies for glibc: linux-headers@5.15
==> Fetching linux-headers@5.15
==> Fetching glibc
==> Fetching dependencies for gcc: gmp, isl, mpfr, libmpc, lz4, xz, zlib, zstd and binutils
==> Fetching gmp
==> Fetching isl
==> Fetching mpfr
==> Fetching libmpc
==> Fetching lz4
==> Fetching xz
==> Fetching zlib
==> Fetching zstd
==> Fetching binutils
==> Fetching gcc
==> Installing dependencies for glibc: linux-headers@5.15
==> Installing glibc dependency: linux-headers@5.15
🍺  /home/linuxbrew/.linuxbrew/Cellar/linux-headers@5.15/5.15.174: 961 files, 5.7MB
==> Installing glibc
==> /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1/sbin/ldconfig
==> Installing locale data for en_US.UTF-8 en_US.utf8
==> /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
==> /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1/bin/localedef -i en_US -f UTF-8 en_US.utf8
==> Caveats
The Homebrew's Glibc has been installed with the following executables:
  /home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd
  /home/linuxbrew/.linuxbrew/opt/glibc/bin/ld.so
  /home/linuxbrew/.linuxbrew/opt/glibc/sbin/ldconfig

By default, Homebrew's linker will not search for the system's libraries. If you
want Homebrew to do so, run:

  cp "/home/linuxbrew/.linuxbrew/etc/ld.so.conf.d/99-system-ld.so.conf.example" "/home/linuxbrew/.linuxbrew/etc/ld.so.conf.d/99-system-ld.so.conf"
  brew postinstall glibc

to append the system libraries to Homebrew's ld search paths. This is risky and
**highly not recommended**, because it may cause linkage to Homebrew libraries
mixed with system libraries.

glibc is keg-only, which means it was not symlinked into /home/linuxbrew/.linuxbrew,
because it can shadow system glibc if linked.

If you need to have glibc first in your PATH, run:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/glibc/bin:$PATH"' >> ~/.profile
  echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/glibc/sbin:$PATH"' >> ~/.profile

For compilers to find glibc you may need to set:
  export LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/glibc/lib"
  export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/glibc/include"
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1: 1,405 files, 47.1MB
==> Running `brew cleanup glibc`...
==> Installing dependencies for gcc: gmp, isl, mpfr, libmpc, lz4, xz, zlib, zstd and binutils
==> Installing gcc dependency: gmp
🍺  /home/linuxbrew/.linuxbrew/Cellar/gmp/6.3.0: 24 files, 3.9MB
==> Installing gcc dependency: isl
🍺  /home/linuxbrew/.linuxbrew/Cellar/isl/0.27: 75 files, 9.9MB
==> Installing gcc dependency: mpfr
🍺  /home/linuxbrew/.linuxbrew/Cellar/mpfr/4.2.1: 32 files, 3.9MB
==> Installing gcc dependency: libmpc
🍺  /home/linuxbrew/.linuxbrew/Cellar/libmpc/1.3.1: 14 files, 644.1KB
==> Installing gcc dependency: lz4
🍺  /home/linuxbrew/.linuxbrew/Cellar/lz4/1.10.0: 24 files, 799.9KB
==> Installing gcc dependency: xz
🍺  /home/linuxbrew/.linuxbrew/Cellar/xz/5.6.3: 97 files, 2MB
==> Installing gcc dependency: zlib
🍺  /home/linuxbrew/.linuxbrew/Cellar/zlib/1.3.1: 14 files, 477.2KB
==> Installing gcc dependency: zstd
🍺  /home/linuxbrew/.linuxbrew/Cellar/zstd/1.5.6: 32 files, 2.9MB
==> Installing gcc dependency: binutils
==> Fetching dependencies for git: libunistring, acl, icu4c@76, ncurses, readline, libxml2, gettext, bzip2, binutils, gcc, pcre2, ca-certificates, openssl@3, brotli, libnghttp2, libssh2, rtmpdump, libidn2, libedit, krb5, libxcrypt, sqlite, util-linux, openldap, curl and expat
==> Fetching libunistring
==> Fetching acl
==> Fetching icu4c@76
==> Fetching ncurses
==> Fetching readline
==> Fetching libxml2
==> Fetching gettext
==> Fetching bzip2
==> Fetching binutils
==> Fetching gcc
==> Installing pcre2 dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
==> Fetching dependencies for ruby: binutils, gcc, libyaml, ca-certificates, openssl@3, gperf, libffi and libxcrypt
==> Fetching binutils
==> Fetching gcc
==> Installing libyaml dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
==> Fetching dependencies for clang-build-analyzer: mpdecimal, ca-certificates, openssl@3, ncurses, readline, sqlite, berkeley-db@5, libedit, krb5, libtirpc, libnsl, bzip2, expat, libffi, libxcrypt, unzip, python@3.13, binutils, gcc, z3, elfutils and llvm
==> Fetching mpdecimal
==> Fetching ca-certificates
==> Fetching openssl@3
==> Fetching ncurses
==> Fetching readline
==> Fetching sqlite
==> Fetching berkeley-db@5
==> Fetching libedit
==> Fetching krb5
==> Fetching libtirpc
==> Fetching libnsl
==> Fetching bzip2
==> Fetching expat
==> Fetching libffi
==> Fetching libxcrypt
==> Fetching unzip
==> Fetching python@3.13
==> Fetching binutils
==> Fetching gcc
==> Installing z3 dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
==> Fetching dependencies for zsh: bzip2, binutils, gcc, pcre and ncurses
==> Fetching bzip2
==> Fetching binutils
==> Fetching gcc
==> Installing pcre dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
==> Fetching dependencies for yq: binutils and gcc
==> Fetching binutils
==> Fetching gcc
==> Installing yq dependency: gcc
==> Installing dependencies for gcc: binutils
==> Installing gcc dependency: binutils
/bin/ls: cannot access '/home/linuxbrew/.linuxbrew/opt/gcc/bin/gcc-*': No such file or directory
--------------------------PATH SET-------------------------------
/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/opt/binutils/bin:/home/linuxbrew/.linuxbrew/opt/glibc/bin:/home/linuxbrew/.linuxbrew/opt/glibc/sbin:/home/linuxbrew/.linuxbrew/lib/ruby/gems/*/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
-----------------------------------------------------------------
Error: The YAML file './config.yaml' is invalid.
⚠️ Script exited with code 1.
🗑️ Removing sudoers file at '/etc/sudoers.d/custom_homebrew_sudoers'...
🗑️ Sudoers file removed.
🔒 Revoking sudo access...
🔒 Sudo access revoked.
```

**Comment by MrCee** [comment]
Im actually yet to fix minimal install. I'm on to it now. 

There was indeed something that changed upstream this morning, it has been fixed since. But yep... full install is what I have just tested as per the above, I need to make some adjustments to minimal install.

**Comment by tanawitsu** [comment]
Thank you for the updates.

**Comment by MrCee** [comment]
@tanawitsu  The main script should be good to go now. When you can, please run the uninstall script and pull a fresh clone of Synology-Homebrew.  Let me know how you go.

**Comment by tanawitsu** [comment]
It's all set. Thanks for your support.
